 NumPy Introduction :
 NumPy is a powerful library for numerical computing in Python. It provides support for arrays 

In [31]:
#Example :
import numpy 

arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [32]:
#Example:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [33]:
#example :
import numpy as np
print(np.__version__)

2.3.0


NumPy Arrays :
NumPy arrays are the core data structure of the NumPy library. They are similar to Python lists but offer better performance and more functionality for numerical operations. 

In [34]:
#create a numpy array ndarray object 

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


Dimensions in Arrays :
A NumPy array can have multiple dimensions, which allows for more complex data structures.

0-D Arrays: 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.



In [35]:
#example :
import numpy as np
arr = np.array(42)
print(arr)
print(arr.ndim) #ndim is an attribute that returns the number of dimensions of the array.

42
0


1-D Arrays: 1-D arrays are like a list of values. They have one dimension.

In [36]:
#example :
import numpy as np 
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)
print(arr_1d.ndim)

[1 2 3 4 5]
1


2-D Arrays: An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors . 

In [37]:
#example : Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6.
import numpy as np 
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(arr_2d.ndim)

[[1 2 3]
 [4 5 6]]
2


3-D Arrays: An array that has 2-D arrays as its elements is called a 3-D array. These are often used to represent a cube or 3rd order tensors.

In [38]:
#example : Create a 3-D array containing two 2-D arrays.
import numpy as np
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [39]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Asssigment :

In [40]:
#Create a 0D array with the value 25 and print its dimension.
import numpy as np
arr = np.array(25)
print(arr)

25


In [41]:
#Make a 1D array containing numbers from 10 to 50 with a step of 10.
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [42]:
#Print the 3rd element of a 1D array [5, 10, 15, 20, 25].
import numpy as np
arr = np.array([5,10,15,20,25])
print(arr[2])

15


In [43]:
#Create a 2D array of shape (2,3) with random integers between 1 and 9.
import numpy as np
arr = np.random.randint(1,10,(2,3))
print(arr)

[[6 3 8]
 [2 2 7]]


In [44]:
#Access the element in the 2nd row, 1st column of that 2D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1,0])

4


In [45]:
#Find the shape and number of dimensions of this array:np.array([[1,2,3],[4,5,6]])
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim) 

(2, 3)
2


In [46]:
#Create a 3D array using np.arange(12).reshape(2,2,3) and print it.
import numpy as np 
arr = np.arange(12).reshape(2,2,3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [47]:
#Access the element in block 2, row 1, column 3 of that 3D array.
import numpy as np
arr = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(arr[1,0,2])
print(arr.ndim)

8
3


In [48]:
#Find the toal number of elements in the 3d array.
import numpy as np
arr = np.arange(12).reshape(2,2,3)
arr = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(arr.size)

12


In [49]:
#Flatten the 3D array into 1D using .ravel() and print the result.
import numpy as np
arr = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
flat_arr = arr.ravel()
print(flat_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


NumPy Array Indexing:
Access Array Elements: Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [50]:
#example :
import numpy as np
arr = np.array([1,2,3,4])
print(arr[0])  # Accessing the first element
print(arr[2])  # Accessing the third element

1
3


In [51]:
#example :
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0]+arr[4])  # Accessing and adding the first and fifth elements
print(arr[2]-arr[6])  # Accessing and subtracting the third and seventh elements
print(arr[1]*arr[3])  # Accessing and multiplying the second and fourth elements
print(arr[8]/arr[5])  # Accessing and dividing the ninth and sixth elements


6
-4
8
1.5


Access 2-D Arrays :
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [52]:
#example :
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("2nd element on 1st row:", arr[0,1])  # Accessing the second element of the first row
print("5th element on 2nd row:", arr[1,4])  # Accessing the fifth element of the second row

2nd element on 1st row: 2
5th element on 2nd row: 10


Access 3-D Arrays :
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [53]:
#example :
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("2nd element of 1st array of 1st dimension:", arr[0,0,1])  # Accessing the second element of the first array in the first dimension
print("3rd element of 2nd array of 2nd dimension:", arr[1,1,2])  # Accessing the third element of the second array in the second dimension

2nd element of 1st array of 1st dimension: 2
3rd element of 2nd array of 2nd dimension: 12


Negative Indexing:Use negative indexing to access an array from the end.

In [54]:
#example :
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Last element:" , arr[1,-1])  # Accessing the last element of the second row
print("2nd last element:", arr[0,-2])  # Accessing the second last element of the first row

Last element: 10
2nd last element: 4


Assignment:

In [55]:
#Create a NumPy array arr = np.array([10, 20, 30, 40, 50]).Q: Access the 3rd element.
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[2])

30


In [56]:
#Print the first and last elements of the same array. 
import numpy as np 
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])

10
50


In [57]:
#Replace the second element (20) with 200.
import numpy as np
arr = np.array([10,20,30,40,50])
arr[1] = 200
print(arr)

[ 10 200  30  40  50]


In [58]:
#Slice the array to get the elements [20, 30, 40].
import numpy as np
arr = np.array([10,20,30,40,50])
sliced_arr = arr[1:4]
print(sliced_arr)

[20 30 40]


In [59]:
#Create a 2D array.Print the element in 2nd row, 3rd element.
import numpy as np 
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[1,2])

6


In [60]:
#Extract the first row.
import numpy as np
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
first_row = arr_2d[0,:] 
print(first_row)

[1 2 3]


Slicing Arrays in NumPy :
Slicing in NumPy is similar to slicing in Python lists. You can specify a start index, an end index, and a step.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0.
If we don't pass end its considered length of array in that dimension.
If we don't pass step its considered 1.

In [61]:
#example : Slice elements from index 1 to index 5 from the following array:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [62]:
#example :Slice elements from index 4 to the end of the array
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[4:])

[5 6 7 8 9]


In [63]:
#example :Slice elements from the beginning to index 4 (not included)
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[:4])

[1 2 3 4]
